version: '3.8'

services:
  db:
    image: postgres
    restart: always
    ports:
      - 5434:5432
    environment:
      - POSTGRES_HOST=localhost
      - POSTGRES_PASSWORD=569641
      - POSTGRES_DB=ayd_project
      - POSTGRES_USER=brayan
    volumes:
      - ./postgres:/var/lib/postgresql/data:rw